using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


//https://projecteuler.net/problem=2

//Even Fibonacci numbers
//Problem 2
            
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



namespace Even_Fibonacci_numbers
{
    class Program
    {
        static void Main(string[] args)
        {
            int maximumFibunacciNumber = 4000000;
            Fibunacci fibunacci = new Fibunacci();

            var sumEvenFibunacciNumbers = fibunacci.SumEvenNumbersUpTo(maximumFibunacciNumber);

            Console.WriteLine("Sum: " + sumEvenFibunacciNumbers);
            Console.ReadKey();

        }
    }
}
